import { test, expect, inProcess } from './helpers/projectFixtures'
import { selectProjectOption } from './helpers/projectSelect'
test.use({ locale: 'zh-CN' })
const unique = (label: string) => `${label}-${Date.now()}-${Math.random().toString(36).slice(2, 7)}`

test('Board restores the milestone and related references with its draft, then creates them atomically', async ({ page, request }) => {
  const area = await (await request.post('/api/areas', { data: { name: unique('任务方向') } })).json()
  const other = await (await request.post('/api/areas', { data: { name: unique('相关成长') } })).json()
  const milestone = await (await request.post('/api/milestones', { data: { areaId: area.id, name: unique('阶段目标') } })).json()
  await page.goto(`/projects/milestones/${milestone.id}`)
  await page.getByRole('button', { name: '新建 Task', exact: true }).click()
  const title = unique('保留归属的草稿')
  await page.getByRole('textbox', { name: '任务标题', exact: true }).fill(title)
  await selectProjectOption(page, '关联方向或里程碑', other.name)
  await page.reload()
  await expect(page.getByRole('textbox', { name: '任务标题', exact: true })).toHaveValue(title)
  await expect(page.getByRole('button', { name: `${area.name} › ${milestone.name}`, exact: true })).toBeVisible()
  await expect(page.getByRole('button', { name: other.name, exact: true })).toBeVisible()
  const createdResponse = page.waitForResponse(response => response.url().endsWith('/api/tasks') && response.request().method() === 'POST')
  await page.getByRole('textbox', { name: '任务标题', exact: true }).press('ControlOrMeta+Enter')
  const created = await (await createdResponse).json()
  expect(created.primaryMilestoneId).toBe(milestone.id)
  const refs = await (await request.get(`/api/project-references?sourceType=task&sourceId=${created.id}`)).json()
  expect(refs.references.some((r: any) => r.targetType === 'area' && r.targetId === other.id)).toBe(true)
})

test('Note metadata links update without sending untouched Note content', async ({ page, request }) => {
  const area = await (await request.post('/api/areas', { data: { name: unique('沉淀方向') } })).json()
  const note = await (await request.post('/api/notes', { data: { title: unique('已有沉淀'), contentHtml: '<p>已经保存的个人感悟。</p>' } })).json()
  const noteWrites: string[] = []
  page.on('request', req => { if (req.method() === 'PUT' && new URL(req.url()).pathname === `/api/notes/${note.id}`) noteWrites.push(req.postData() || '') })
  await page.goto(`/notes?id=${note.id}`)
  const relations = page.getByTestId('project-relations')
  const linked = page.waitForResponse(response => response.url().endsWith('/api/project-references') && response.request().method() === 'PUT')
  await selectProjectOption(page, '关联方向或里程碑', area.name)
  expect((await linked).ok()).toBe(true)
  await relations.getByRole('button', { name: area.name, exact: true }).click()
  await expect(page.getByRole('heading', { name: area.name, exact: true })).toBeVisible()
  expect(noteWrites).toEqual([])
  const current = await (await request.get(`/api/notes/${note.id}`)).json()
  expect(current.contentHtml).toBe(note.contentHtml)
  expect(current.revision).toBe(note.revision)
})

test('SSE refreshes project labels and assignment effort across windows while an unsaved Note stays intact', async ({ page, context, request }) => {
  test.skip(inProcess, 'Cross-window SSE requires the real HTTP event stream')
  test.setTimeout(90_000)
  const area = await (await request.post('/api/areas', { data: { name: unique('跨窗口方向') } })).json()
  const first = await (await request.post('/api/milestones', { data: { areaId: area.id, name: unique('原里程碑') } })).json()
  const second = await (await request.post('/api/milestones', { data: { areaId: area.id, name: unique('新里程碑') } })).json()
  const task = await (await request.post('/api/tasks', { data: { title: unique('跨窗口任务'), type: 'TODO', priority: 'MEDIUM', primaryMilestoneId: first.id } })).json()
  const note = await (await request.post('/api/notes', { data: { title: unique('本地笔记'), contentHtml: '<p>服务器原始内容。</p>' } })).json()
  const linked = await request.put('/api/project-references', { data: { sourceType: 'note', sourceId: note.id, expectedRevision: 1, references: [{ targetType: 'milestone', targetId: first.id, role: 'growth' }] } })
  expect(linked.ok(), await linked.text()).toBe(true)
  // Fixture-only ended work session makes the before/after effort observable.
  const { createRequire } = await import('node:module')
  const path = await import('node:path')
  const Database = createRequire(path.resolve('server/package.json'))('better-sqlite3')
  const directory = process.env.CHRONICLE_TEST_DATA_DIR
  if (!directory) throw new Error('Isolated project-test database required')
  const db = new Database(path.join(directory, 'tasks.db'))
  try { const end = Date.now() - 60_000; db.prepare('INSERT INTO work_sessions(id,task_id,started_at,ended_at) VALUES(?,?,?,?)').run(unique('fixture-session'), task.id, end - 7_200_000, end) } finally { db.close() }

  const overview = await context.newPage()
  const editor = await context.newPage()
  let releaseSave!: () => void
  const saveGate = new Promise<void>(resolve => { releaseSave = resolve })
  let saveStarted = false
  await page.route(`**/api/notes/${note.id}`, async route => {
    if (route.request().method() === 'PUT') { saveStarted = true; await saveGate }
    await route.continue()
  })
  try {
    await Promise.all([page.goto(`/notes?id=${note.id}`), overview.goto('/projects'), editor.goto(`/projects/milestones/${first.id}`)])
    await overview.getByRole('button', { name: '投入与成果', exact: true }).click()
    await Promise.all([expect(page.getByTitle('connected', { exact: true })).toBeVisible(), expect(overview.getByTitle('connected', { exact: true })).toBeVisible(), expect(editor.getByTitle('connected', { exact: true })).toBeVisible()])
    await selectProjectOption(overview, '统计期间', '全部时间')
    const firstCard = () => overview.locator(`[data-testid=milestone-card][data-project-object="milestone:${first.id}"]`)
    const secondCard = () => overview.locator(`[data-testid=milestone-card][data-project-object="milestone:${second.id}"]`)
    await expect(firstCard().getByText('2.0 小时', { exact: true })).toBeVisible()
    await expect(secondCard().getByText('0 分钟', { exact: true })).toBeVisible()
    const body = page.locator('.ProseMirror[contenteditable="true"]')
    const draftText = unique('尚未提交的个人感悟')
    await body.fill(draftText)
    await expect.poll(() => saveStarted).toBe(true)

    await editor.locator('summary').filter({ hasText: '属性与管理历史' }).click()
    await editor.getByRole('button', { name: '编辑属性', exact: true }).click()
    const renamed = unique('跨窗口重命名')
    await editor.getByRole('dialog').getByRole('textbox', { name: '名称', exact: true }).fill(renamed)
    await editor.getByRole('dialog').getByRole('button', { name: '保存', exact: true }).click()
    await expect(editor.getByRole('heading', { name: renamed, exact: true })).toBeVisible()
    await expect(page.getByTestId('project-relations').getByRole('button', { name: `${area.name} › ${renamed}`, exact: true })).toBeVisible()
    await expect(firstCard()).toContainText(renamed)
    await expect(body).toContainText(draftText)
    expect((await (await request.get(`/api/notes/${note.id}`)).json()).contentHtml).toBe(note.contentHtml)

    await editor.goto('/')
    await editor.locator(`[data-task-id="${task.id}"]`).click()
    await editor.getByRole('button', { name: '调整归属', exact: true }).click()
    const assignment = editor.getByRole('dialog')
    await selectProjectOption(editor, '选择主里程碑', second.name)
    await assignment.getByRole('button', { name: '预览变更', exact: true }).click()
    await expect(assignment.getByText('里程碑投入', { exact: true })).toBeVisible()
    await assignment.getByRole('button', { name: '确认归属', exact: true }).click()
    await expect(assignment.getByRole('heading', { name: '已更新 1 个任务的归属', exact: true })).toBeVisible()
    await assignment.getByRole('button', { name: '完成', exact: true }).click()
    await expect(editor.getByTestId('project-relations').getByRole('button', { name: `${area.name} › ${second.name}`, exact: true })).toBeVisible()
    await expect(secondCard().getByText('2.0 小时', { exact: true })).toBeVisible()
    await expect(firstCard().getByText('0 分钟', { exact: true })).toBeVisible()
    await expect(body).toContainText(draftText)
    // Releasing the user's one pending edit saves it normally after the SSE updates.
    releaseSave()
    await expect.poll(async () => (await (await request.get(`/api/notes/${note.id}`)).json()).contentHtml).toContain(draftText)
    await expect(body).toContainText(draftText)
  } finally {
    releaseSave()
    await Promise.all([overview.close(), editor.close()])
  }
})

test('stage completion, handwritten Note review and later edits preserve the confirmed history', async ({ page, request }) => {
  test.setTimeout(75_000)
  const area = await (await request.post('/api/areas', { data: { name: unique('复盘方向') } })).json()
  const milestone = await (await request.post('/api/milestones', { data: { areaId: area.id, name: unique('人工验收里程碑'), goal: '验证结果并保留经验', completionCriteria: '已经核对实际成果' } })).json()
  await page.goto(`/projects/milestones/${milestone.id}`)
  await page.getByRole('button', { name: '完成里程碑', exact: true }).click()
  const edit = page.getByRole('dialog')
  await expect(edit).toContainText('已经核对实际成果')
  await edit.getByRole('checkbox', { name: '我已核对成果，确认里程碑完成。复盘可以稍后补充。', exact: true }).check()
  await edit.getByRole('button', { name: '确认完成并保存', exact: true }).click()
  await expect(page.getByText('里程碑已完成。整理这次成果与经验，也可以稍后继续。', { exact: true })).toBeVisible()
  await page.getByRole('button', { name: '新建完成复盘', exact: true }).click()
  await expect(page).toHaveURL(/\/notes\?id=/)
  const noteId = new URL(page.url()).searchParams.get('id')!
  const firstText = unique('第一次确认的实践经验')
  await page.locator('.ProseMirror[contenteditable="true"]').fill(firstText)
  await expect.poll(async () => (await (await request.get(`/api/notes/${noteId}`)).json()).contentHtml).toContain(firstText)
  const review = (await (await request.get(`/api/project-reviews?targetType=milestone&targetId=${milestone.id}`)).json())[0]
  expect(review.status).toBe('draft')
  expect((await (await request.get(`/api/milestones/${milestone.id}`)).json()).reviewStatus).toBe('pending')
  const reviewContext = page.getByTestId('project-review-context')
  await reviewContext.getByRole('button', { name: '保存并确认回顾', exact: true }).click()
  await expect(reviewContext.getByText('已确认版本 1', { exact: true }).first()).toBeVisible()
  await reviewContext.getByRole('button', { name: `返回 ${milestone.name}`, exact: true }).click()
  await expect(page.getByText('完成复盘 · 已确认', { exact: true })).toBeVisible()
  await expect(page.getByTestId('project-review-card')).toContainText(firstText)
  await page.getByRole('button', { name: '编辑 Note', exact: true }).click()
  const laterText = unique('后来形成的新认识')
  await page.locator('.ProseMirror[contenteditable="true"]').fill(laterText)
  await expect.poll(async () => (await (await request.get(`/api/notes/${noteId}`)).json()).contentHtml).toContain(laterText)
  await expect(page.getByTestId('project-review-context')).toContainText('当前有新编辑，尚未纳入已确认版本。')
  await page.getByTestId('project-review-context').getByRole('button', { name: `返回 ${milestone.name}`, exact: true }).click()
  await expect(page.getByText('Note 在确认后有新修改', { exact: false })).toBeVisible()
  await page.getByRole('button', { name: '核对 / 版本', exact: true }).click()
  const versions = page.getByRole('dialog')
  await expect(versions).toContainText(laterText)
  const firstVersion = versions.locator('details').filter({ has: page.locator('summary').filter({ hasText: /^版本 1/ }) }).first()
  await expect(firstVersion).toContainText(firstText)
  await expect(firstVersion).not.toContainText(laterText)
  const saved = await (await request.get(`/api/project-reviews/${review.id}`)).json()
  expect(saved.versions).toHaveLength(1)
  expect(saved.versions[0].contentHtml).toContain(firstText)
  expect(saved.confirmedPreview).toContain(firstText)
  expect(saved.confirmedPreview).not.toContain(laterText)
  expect(saved.noteChangedSinceConfirmation).toBe(true)
})

test('a failed LLM draft can be retried with a larger independent output budget', async ({ page, request }) => {
  test.setTimeout(60_000)
  const originalSettings = await (await request.get('/api/settings/llm')).json()
  const area = await (await request.post('/api/areas', { data: { name: unique('预算方向') } })).json()
  const milestone = await (await request.post('/api/milestones', { data: { areaId: area.id, name: unique('输出预算里程碑') } })).json()
  let retryId: string | undefined
  try {
    // A deliberately unavailable local provider gives a deterministic failure without spending tokens.
    const configured = await request.put('/api/settings/llm', { data: { baseUrl: 'http://127.0.0.1:1/v1', model: 'project-ui-unavailable-provider', apiKey: '', timeoutMs: 1000 } })
    expect(configured.ok(), await configured.text()).toBe(true)
    await page.goto(`/projects/milestones/${milestone.id}`)
    await page.getByTestId('project-reviews').locator('summary').filter({ hasText: '高级设置' }).click()
    const budget = page.getByRole('button', { name: '输出与推理预算', exact: true })
    await expect(budget).toHaveText('4,000 tokens')
    await budget.click()
    await page.getByRole('option', { name: '8,000 tokens', exact: true }).click()
    const createdResponse = page.waitForResponse(response => new URL(response.url()).pathname === '/api/project-insights' && response.request().method() === 'POST')
    await page.getByRole('button', { name: '生成 LLM 回顾草稿', exact: true }).click()
    const response = await createdResponse
    expect(response.ok()).toBe(true)
    expect(response.request().postDataJSON().budget.maxOutputTokens).toBe(8000)
    const originalDraft = await response.json()
    await expect.poll(async () => (await (await request.get(`/api/project-insights/${originalDraft.id}`)).json()).status).toBe('error')
    await expect(page.getByText('生成失败', { exact: false })).toBeVisible()
    await budget.click()
    await page.getByRole('option', { name: '16,000 tokens', exact: true }).click()
    const retriedResponse = page.waitForResponse(result => new URL(result.url()).pathname === `/api/project-insights/${originalDraft.id}/retry` && result.request().method() === 'POST')
    await page.getByRole('button', { name: '重新生成', exact: true }).click()
    const retried = await retriedResponse
    expect(retried.ok()).toBe(true)
    expect(retried.request().postDataJSON().budget.maxOutputTokens).toBe(16000)
    const draft = await retried.json()
    retryId = draft.id
    expect(draft.budget.maxOutputTokens).toBe(16000)
    expect(draft.previousDraftId).toBe(originalDraft.id)
    const previous = await (await request.get(`/api/project-insights/${originalDraft.id}`)).json()
    expect(previous.status).toBe('error')
    expect(previous.budget.maxOutputTokens).toBe(8000)
  } finally {
    if (retryId) await request.post(`/api/project-insights/${retryId}/cancel`)
    await request.put('/api/settings/llm', { data: originalSettings })
  }
})
