import { test, expect } from './helpers/projectFixtures'
import { selectProjectOption } from './helpers/projectSelect'

test.use({ locale: 'en-US' })
const unique = (name: string) => `${name}-${Date.now()}-${Math.random().toString(36).slice(2, 6)}`

test('Board project filtering supports search, keyboard selection and focus return without native selects', async ({ page, request }) => {
  const area = await (await request.post('/api/areas', { data: { name: unique('Platform') } })).json()
  const milestone = await (await request.post('/api/milestones', { data: { areaId: area.id, name: unique('Reliability') } })).json()
  const title = unique('Visible milestone task')
  await request.post('/api/tasks', { data: { title, type: 'TODO', priority: 'MEDIUM', primaryMilestoneId: milestone.id } })
  await page.goto('/')
  const trigger = page.getByRole('button', { name: 'Filter by area or milestone', exact: true })
  await trigger.click()
  const popup = page.locator('[data-project-select-popup]')
  await popup.getByRole('combobox').fill(milestone.name)
  await expect(popup.getByRole('option')).toHaveCount(1)
  await expect(popup.getByRole('option')).toContainText(area.name)
  await popup.getByRole('combobox').press('Enter')
  await expect(trigger).toBeFocused()
  await expect(page.locator('[data-task-id]')).toHaveCount(1)
  await expect(page.locator('[data-task-id]')).toContainText(title)
  await trigger.press('Enter')
  await popup.getByRole('combobox').fill('No matching milestone')
  await expect(popup.getByRole('status')).toHaveText('No matching results')
  await popup.getByRole('combobox').press('Escape')
  await expect(trigger).toBeFocused()
  await expect(page.locator('select')).toHaveCount(0)
})

test('Task selection never opens or starts another task and Escape only exits selection', async ({ page, request }) => {
  const first = await (await request.post('/api/tasks', { data: { title: unique('Current work'), type: 'TODO', priority: 'MEDIUM' } })).json()
  const other = await (await request.post('/api/tasks', { data: { title: unique('Select this task'), type: 'TODO', priority: 'MEDIUM' } })).json()
  await request.post(`/api/tasks/${first.id}/takeover`)
  await page.goto('/')
  await page.locator(`[data-task-id="${first.id}"]`).click()
  await expect(page.getByTestId('workspace-info-bar')).toBeVisible()
  const editor = page.locator('.ProseMirror[contenteditable="true"]')
  const draftText = unique('Keep my unfinished log')
  await editor.fill(draftText)
  const writes: string[] = []
  page.on('request', req => { if (req.method() !== 'GET' && /\/(takeover|start|logs)$/.test(new URL(req.url()).pathname)) writes.push(req.url()) })
  await page.getByRole('button', { name: 'Select tasks', exact: true }).click()
  const row = page.getByRole('checkbox', { name: `Select ${other.title}`, exact: true })
  await row.click()
  await expect(row).toBeChecked()
  await expect(page.getByRole('toolbar', { name: 'Task selection actions' })).toContainText('1 selected')
  await expect(editor).toContainText(draftText)
  await row.press('Space')
  await expect(row).not.toBeChecked()
  await row.press('Enter')
  await expect(row).toBeChecked()
  await row.press('ArrowUp')
  await expect(page.getByRole('checkbox', { name: `Select ${first.title}`, exact: true })).toBeFocused()
  await page.keyboard.press('Escape')
  await expect(page.getByRole('toolbar', { name: 'Task selection actions' })).not.toBeVisible()
  await expect(page.getByRole('button', { name: 'Select tasks', exact: true })).toBeFocused()
  await expect(editor).toContainText(draftText)
  expect(writes).toEqual([])
  expect((await (await request.get('/api/sessions/current')).json()).taskId).toBe(first.id)
  await request.post('/api/afk')
})

test('Bulk assignment previews an explicit target, survives filtered rows changing and undoes atomically', async ({ page, request }) => {
  const area = await (await request.post('/api/areas', { data: { name: unique('Delivery') } })).json()
  const first = await (await request.post('/api/milestones', { data: { areaId: area.id, name: unique('Current milestone') } })).json()
  const target = await (await request.post('/api/milestones', { data: { areaId: area.id, name: unique('Next milestone') } })).json()
  const tasks = []
  for (const title of ['First task', 'Second task']) tasks.push(await (await request.post('/api/tasks', { data: { title: unique(title), type: 'TODO', priority: 'MEDIUM', primaryMilestoneId: first.id } })).json())
  await page.goto(`/?projectFilter=milestone:${first.id}`)
  await page.getByRole('button', { name: 'Select tasks', exact: true }).click()
  const toolbar = page.getByRole('toolbar', { name: 'Task selection actions' })
  await toolbar.getByRole('button', { name: 'All', exact: true }).click()
  await expect(toolbar).toContainText('2 selected')
  await toolbar.getByRole('button', { name: 'Assign…', exact: true }).click()
  const dialog = page.getByRole('dialog', { name: 'Assign milestone', exact: true })
  await expect(dialog.getByRole('button', { name: 'Preview changes', exact: true })).toBeDisabled()
  await selectProjectOption(page, 'Choose milestone', target.name)
  await dialog.getByRole('button', { name: 'Preview changes', exact: true }).click()
  const review = page.getByRole('dialog', { name: 'Review changes', exact: true })
  await expect(review).toContainText(target.name)
  for (const task of tasks) expect((await (await request.get(`/api/tasks/${task.id}`)).json()).primaryMilestoneId).toBe(first.id)
  await review.getByRole('button', { name: 'Apply assignment', exact: true }).click()
  const saved = page.getByRole('dialog', { name: 'Updated 2 tasks', exact: true })
  await expect(saved).toBeVisible()
  for (const task of tasks) expect((await (await request.get(`/api/tasks/${task.id}`)).json()).primaryMilestoneId).toBe(target.id)
  await saved.getByRole('button', { name: 'Undo assignment', exact: true }).click()
  await expect(saved).not.toBeVisible()
  for (const task of tasks) expect((await (await request.get(`/api/tasks/${task.id}`)).json()).primaryMilestoneId).toBe(first.id)
  await expect(page.getByRole('checkbox')).toHaveCount(2)
})

test('Selection clears explicitly and cancelling assignment preserves the selected tasks', async ({ page, request }) => {
  const task = await (await request.post('/api/tasks', { data: { title: unique('Keep selection'), type: 'TODO', priority: 'MEDIUM' } })).json()
  await page.goto('/')
  await page.getByRole('button', { name: 'Select tasks', exact: true }).click()
  await page.getByRole('checkbox', { name: `Select ${task.title}`, exact: true }).click()
  const toolbar = page.getByRole('toolbar', { name: 'Task selection actions' })
  const assign = toolbar.getByRole('button', { name: 'Assign…', exact: true })
  await assign.click()
  await page.getByRole('dialog', { name: 'Assign milestone', exact: true }).getByRole('button', { name: 'Cancel', exact: true }).click()
  await expect(page.getByRole('checkbox', { name: `Select ${task.title}`, exact: true })).toBeChecked()
  await expect(assign).toBeFocused()
  await toolbar.getByRole('button', { name: 'Clear', exact: true }).click()
  await expect(assign).toBeDisabled()
  await expect(toolbar).toContainText('0 selected')
})

test('Selection shortcuts stay in the list while the existing detail editor keeps Escape and submit behavior', async ({ page, request }) => {
  const task = await (await request.post('/api/tasks', { data: { title: unique('Continue editing in detail'), type: 'TODO', priority: 'MEDIUM' } })).json()
  await page.goto('/')
  await page.locator(`[data-task-id="${task.id}"]`).click()
  await expect(page.getByTestId('workspace-info-bar')).toBeVisible()
  await page.getByRole('button', { name: 'Select tasks', exact: true }).click()
  await expect(page.getByRole('checkbox', { name: `Select ${task.title}`, exact: true })).toBeFocused()
  const editor = page.locator('.ProseMirror[contenteditable="true"]')
  const text = unique('A log written while selecting tasks')
  await editor.fill(text)
  await editor.press('Escape')
  await expect(page.getByRole('toolbar', { name: 'Task selection actions' })).toBeVisible()
  await expect(editor).toContainText(text)
  await editor.click()
  const submitted = page.waitForResponse(response => new URL(response.url()).pathname === `/api/tasks/${task.id}/logs` && response.request().method() === 'POST')
  await editor.press('ControlOrMeta+Enter')
  expect((await submitted).ok()).toBe(true)
  await expect(page.getByRole('toolbar', { name: 'Task selection actions' })).toBeVisible()
  const entries = await (await request.get(`/api/tasks/${task.id}/logs`)).json()
  expect(entries.some((entry: { content: string }) => entry.content.includes(text))).toBe(true)
})

test('New task shortcut follows the current milestone filter and its clearing, without relying on a stale URL', async ({ page, request }) => {
  const area = await (await request.post('/api/areas', { data: { name: unique('Keyboard planning') } })).json()
  const milestone = await (await request.post('/api/milestones', { data: { areaId: area.id, name: unique('Plan with shortcuts') } })).json()
  await page.goto('/')
  await selectProjectOption(page, 'Filter by area or milestone', milestone.name)
  await page.keyboard.press('ControlOrMeta+n')
  const title = page.getByRole('textbox', { name: 'Task title', exact: true })
  await expect(title).toBeVisible()
  await expect(page.getByRole('button', { name: `${area.name} › ${milestone.name}`, exact: true })).toBeVisible()
  await title.fill(unique('Keyboard planned task'))
  const firstCreated = page.waitForResponse(response => new URL(response.url()).pathname === '/api/tasks' && response.request().method() === 'POST')
  await title.press('ControlOrMeta+Enter')
  expect((await (await firstCreated).json()).primaryMilestoneId).toBe(milestone.id)

  // Start with a milestone in the URL and then clear it in the visible UI.
  await page.goto(`/?projectFilter=milestone:${milestone.id}`)
  await page.getByRole('button', { name: 'Clear project filter', exact: true }).click()
  await page.getByRole('button', { name: 'Filter by area or milestone', exact: true }).focus()
  await page.keyboard.press('ControlOrMeta+n')
  await expect(title).toBeVisible()
  await title.fill(unique('Keyboard unassigned task'))
  const secondCreated = page.waitForResponse(response => new URL(response.url()).pathname === '/api/tasks' && response.request().method() === 'POST')
  await title.press('ControlOrMeta+Enter')
  const response = await secondCreated
  expect(response.request().postDataJSON()).not.toHaveProperty('primaryMilestoneId')
  expect((await response.json()).primaryMilestoneId).toBeNull()
})
